backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: "Homepage"
    name: "homepage"
    files:
      - label: "Hero Image Section"
        name: "heroSection"
        file: "site/data/home/heropanel.yml"
        fields:
          - {label: Title, name: title, widget: hidden}
          - {label: Hero Image Overlay Text, name: tagline, widget: string}
      - label: "Panel 2 Intro"
        name: "panelTwo"
        file: "site/data/home/paneltwo.yml"
        fields:
          - {label: Introductory Text, name: introText, widget: string}
          - {label: Image, name: introImage, widget: image, required: false}
      - label: "Panel 3 Images and Text"
        name: "panelThree"
        file: "site/data/home/panelthree.yml"
        fields:
          - {label: Header, name: header, widget: string, required: false}
          - {label: Image One, name: circleImageOne, widget: image, required: false} 
          - {label: Image One Text, name: circleTextOne, widget: string, required: false}
          - {label: Image Two, name: circleImageTwo, widget: image, required: false} 
          - {label: Image Two Text, name: circleTextTwo, widget: string, required: false}
          - {label: Image Three, name: circleImageThree, widget: image, required: false} 
          - {label: Image Three Text, name: circleTextThree, widget: string, required: false}
      - label: "Panel 4 How We Work"
        name: "panelFour"
        file: "site/data/home/panel4hww.yml"
        fields:
          - {label: Header, name: header, widget: string, required: false} 
          - {label: Body, name: body, widget: string, required: false}
          - {label: Button Text, name: buttonText, widget: string, required: false} 
          - {label: Image, name: image, widget: image, required: false}
      - label: "Panel 5 Teacher Voices"
        name: "panelFive"
        file: "site/data/home/panel5tv.yml"
        fields:
          - {label: Header, name: header, widget: string, required: false} 
          - {label: Button Text, name: buttonText, widget: string, required: false} 
          - label: Quotes 
            name: quotes
            widget: list
            fields:
              - {label: Quote, name: quote, widget: string, required: false}  
      - label: "Panel 6 Our Impact"
        name: "panelSix"
        file: "site/data/home/panel6impact.yml"
        fields:
          - {label: Header, name: header, widget: string, required: false} 
          - {label: Quantity One, name: quantityOne, widget: string, required: false}
          - {label: Text One, name: textOne, widget: string, required: false}
          - {label: Quantity Two, name: quantityTwo, widget: string, required: false}
          - {label: Text Two, name: textTwo, widget: string, required: false} 
          - {label: Quantity Three, name: quantityThree, widget: string, required: false}
          - {label: Text Three, name: textThree, widget: string, required: false} 

  - label: "How We Work"
    name: "howWeWork"
    files:
      - label: "Content Blocks"
        name: "contentBlocks"
        file: "site/data/how-we-work/contents.yml"
        fields:
          - {label: Title, name: title, widget: hidden}
          - label: Blocks
            name: block
            widget: list
            fields:
              - {label: Header, name: header, widget: string}
              - {label: Body, name: body, widget: markdown}

  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "/site/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Blog Post Title", name: "title", widget: "string"}
      - {label: "Created Date", name: "date", widget: "datetime"}
      - {label: "Author Name", name: "postauthorname", widget: "string"}
      - {label: "Author Title", name: "postauthortitle", widget: "string"}  
      - {label: "Author Photo", name: "authorpic", widget: "image", required: false}  
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Social Media / Search Description", name: "description", widget: "string", required: false}
      - {label: "Excerpt for Articles List", name: "listSummary", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", buttons: [bold, italic, link, bulleted-list, numbered-list]}

  - label: "USA Map"
    name: usaMap
    files:
      - label: "Active / Inactive US States"
        name: activeStates
        file: "site/data/mapSVG/states.yml"
        fields:
          - {label: "AL", name: "AL", widget: "boolean", required: false, default: false}
          - {label: "AK", name: "AK", widget: "boolean", required: false, default: false}
          - {label: "AZ", name: "AZ", widget: "boolean", required: false, default: false}
          - {label: "AR", name: "AR", widget: "boolean", required: false, default: false}
          - {label: "CA", name: "CA", widget: "boolean", required: false, default: false}
          - {label: "CO", name: "CO", widget: "boolean", required: false, default: false}
          - {label: "CT", name: "CT", widget: "boolean", required: false, default: false}
          - {label: "DE", name: "DE", widget: "boolean", required: false, default: false}
          - {label: "DC", name: "DC", widget: "boolean", required: false, default: false}            
          - {label: "FL", name: "FL", widget: "boolean", required: false, default: false}
          - {label: "GA", name: "GA", widget: "boolean", required: false, default: false}
          - {label: "HI", name: "HI", widget: "boolean", required: false, default: false}
          - {label: "ID", name: "ID", widget: "boolean", required: false, default: false}
          - {label: "IL", name: "IL", widget: "boolean", required: false, default: false}
          - {label: "IN", name: "IN", widget: "boolean", required: false, default: false}
          - {label: "IA", name: "IA", widget: "boolean", required: false, default: false}
          - {label: "KS", name: "KS", widget: "boolean", required: false, default: false}
          - {label: "KY", name: "KY", widget: "boolean", required: false, default: false}
          - {label: "LA", name: "LA", widget: "boolean", required: false, default: false}
          - {label: "ME", name: "ME", widget: "boolean", required: false, default: false}
          - {label: "MD", name: "MD", widget: "boolean", required: false, default: false}
          - {label: "MA", name: "MA", widget: "boolean", required: false, default: false}
          - {label: "MI", name: "MI", widget: "boolean", required: false, default: false}
          - {label: "MN", name: "MN", widget: "boolean", required: false, default: false}
          - {label: "MS", name: "MS", widget: "boolean", required: false, default: false}
          - {label: "MO", name: "MO", widget: "boolean", required: false, default: false}
          - {label: "MT", name: "MT", widget: "boolean", required: false, default: false}
          - {label: "NE", name: "NE", widget: "boolean", required: false, default: false}
          - {label: "NV", name: "NV", widget: "boolean", required: false, default: false}
          - {label: "NH", name: "NH", widget: "boolean", required: false, default: false}
          - {label: "NJ", name: "NJ", widget: "boolean", required: false, default: false}
          - {label: "NM", name: "NM", widget: "boolean", required: false, default: false}
          - {label: "NY", name: "NY", widget: "boolean", required: false, default: false}
          - {label: "NC", name: "NC", widget: "boolean", required: false, default: false}
          - {label: "ND", name: "ND", widget: "boolean", required: false, default: false}
          - {label: "OH", name: "OH", widget: "boolean", required: false, default: false}
          - {label: "OK", name: "OK", widget: "boolean", required: false, default: false}
          - {label: "OR", name: "OR", widget: "boolean", required: false, default: false}
          - {label: "PA", name: "PA", widget: "boolean", required: false, default: false}
          - {label: "RI", name: "RI", widget: "boolean", required: false, default: false}
          - {label: "SC", name: "SC", widget: "boolean", required: false, default: false}
          - {label: "SD", name: "SD", widget: "boolean", required: false, default: false}
          - {label: "TN", name: "TN", widget: "boolean", required: false, default: false}
          - {label: "TX", name: "TX", widget: "boolean", required: false, default: false}
          - {label: "UT", name: "UT", widget: "boolean", required: false, default: false}
          - {label: "VT", name: "VT", widget: "boolean", required: false, default: false}
          - {label: "VA", name: "VA", widget: "boolean", required: false, default: false}
          - {label: "WA", name: "WA", widget: "boolean", required: false, default: false}
          - {label: "WV", name: "WV", widget: "boolean", required: false, default: false}
          - {label: "WI", name: "WI", widget: "boolean", required: false, default: false}
          - {label: "WY", name: "WY", widget: "boolean", required: false, default: false}
              
  - label: "Newsletter Subscribe Panel"
    name: "newsletter"
    files:
      - label: "Panel Text and Buttons"
        name: "newsletterSection"
        file: "site/data/newsletter/content.yml"
        fields:
          - {label: Title, name: title, widget: hidden}
          - {label: Signup Call to Action, name: cta, widget: string}
          - {label: Email address field text, name: email, widget: string} 
          - {label: Button text, name: button, widget: string}

  - label: "Contact Form"
    name: "contact"
    files:
      - label: "Contact Address"
        name: "contactAdress"
        file: "site/data/contact/contents.yml"
        fields:
          - {label: Title, name: title, widget: hidden}
          - {label: Contact Address, name: contact, widget: markdown, buttons: [bold, italic, link]}

  - label: "Footer"
    name: "footer"
    files:
      - label: "Footer Elements"
        name: "footerElements"
        file: "site/data/footer/contents.yml"
        fields:
          - {label: Title, name: title, widget: hidden}
          - {label: Footer Logo, name: footerLogo, widget: image, required: false}
          - {label: Sponsors Text, name: sponsorText, widget: string, required: false}  
          - label: Sponsor Logos 
            name: sponsorLogos
            widget: list
            required: false
            fields:
              - {label: Logo, name: logo, widget: image, required: false}        
          